### ISSUE TITLE
Invalid message when 0x01 withdrawal address is provided

### ISSUE THREAD

**Issue by xenowits** [gobitfly/eth2-beaconchain-explorer#1854] opened 2023-02-24 03:34 UTC
**Describe the bug**

Dashboard shows `To receive payouts you need 0x01 withdrawal credentials` even though a validator is activated with a valid 0x01 ethereum address.

**To Reproduce**
1. Go to [this link](https://prater.beaconcha.in/validator/b09a0507ff217d60d244b68c8b27a2301137385fbdf1a5be854823029425ac09a51d7cbf8fc16e1eed2b3f0e889c81a2)
2. Click on the last icon in the list of icons which start from blocks, attestations, sync participants etc.
3. Hover over the last icon, ie, the withdrawal icon.

**Expected behavior**

* For validators **WITH** 0x01 withdrawal credentials, show `Withdrawals processed for this validator`
* For validators **WITHOUT** 0x01 withdrawal credentials, show `To receive payouts you need 0x01 withdrawal credentials`

**Screenshots**

<img width="1031" alt="Screenshot 2023-02-24 at 08 53 33" src="https://user-images.githubusercontent.com/43061995/221085358-486ea318-80bc-45d2-a03e-a2106bee8c74.png">

**Desktop (please complete the following information):**
 - MacOS Ventura 13.0.1
 - Google chrome
 - Version 109.0.5414.119 (Official Build) (arm64)

**Additional context**
Seems something's wrong with the control flow [here](https://github.com/gobitfly/eth2-beaconchain-explorer/blob/bf5a85d731ec80cea847d1fc9108451349b399cd/templates/validator/overview.html#L238).

**Comment by recy21** [comment] 2023-05-01 13:11
Thank you for your interest in our project.

There was a lot of "work in progress" live on Prater before the hard fork. I can't reproduce it in current version, so will close it as "can't reproduce".

**Closed by recy21** 2023-05-01 13:11 UTC
