### ISSUE TITLE
old dashboard tab clobbered by new one

### ISSUE THREAD

**Issue by stefantalpalaru** [gobitfly/eth2-beaconchain-explorer#280] opened 2020-10-03 16:05 UTC
Open this in a browser tab: https://spadina.beaconcha.in/dashboard?validators=2162,2163,2168,2170,2171,2172,2173,2174,2175,2176

Now open this other link in another tab: https://spadina.beaconcha.in/dashboard?validators=2180,2181,2182,2183,2184,2185,2186,2187,2188,2189

Go to the first tab and notice that it has been changed to match the second one.

This might have something to do with `window.history.replaceState(null, 'Dashboard', newUrl)` in "js/dashboard.js".

**Comment by guybrush** [comment] 2020-10-09 09:06
Yes this is intended behavior, we store the selected validators in your browser and also sync multiple browser tabs.

In our opinion this makes more sense than having to setup your dashboard again and again.

To use multiple dashboards we recommend to use bookmarks.

**Comment by guybrush** [comment] 2020-10-09 09:08
Please note that this is not set in stone, we are still looking for ways to improve all the things :)

I will not close this ticket for now, maybe others have input/thoughts about this.

**Comment by stefantalpalaru** [comment] 2020-10-09 10:35
> this is intended behavior

You're doing it wrong. Browser tabs are supposed to be separated.

**Closed** 2021-12-22 13:28 UTC
