### ISSUE TITLE
Display stake distribution among validators

### ISSUE THREAD

**Issue by alfredonodo** [gobitfly/eth2-beaconchain-explorer#1302] opened 2022-04-28 15:53 UTC
Hi,
it would be interesting to have a diagram showing the distribution of stakes among validators. 32 ETH are needed to participate in the validation, how many validators own 33%, 51% and 67% of the coins?
Thank you

**Comment by alfredonodo** [comment] 2022-04-29 06:26
Correct. Ethereum 2.0 encourages decentralisation by limiting the amount needed to participate as a validator to 32 ETH. A whale, e.g. a CEX or a DEX, holding X ETH could divide them into N wallets and participate as N validators. It would be useful to be able to see the distribution/concentration of the stake among the various validators i.e. the number of unique validators and unique depositors.

**Comment by qu0b** [comment] 2022-04-29 07:10
We do have some context around this question here: https://beaconcha.in/pools although more addresses need to be indexed to give a more accurate picture.

**Comment by Sagor2214** [comment] 2022-04-29 11:26
2881

**Comment by alfredonodo** [comment] 2022-04-29 14:22
> We do have some context around this question here: https://beaconcha.in/pools although more addresses need to be indexed to give a more accurate picture.

Thanks for the link. I am aware of it, however the data does not seem to be up to date especially compared to https://etherscan.io/dashboards/beacon-depositors
One advantage of beaconchain explorer is that it shows the number of validators per pool. It would be nice to have up-to-date and downloadable data.

**Comment by Buttaa** [comment] 2022-05-13 08:02
duplicate of https://github.com/gobitfly/eth2-beaconchain-explorer/issues/1325

**Closed** 2022-09-28 08:52 UTC
