### ISSUE TITLE
Request a missed attestation threshold for notifications

### ISSUE THREAD

**Issue by superphiz** [gobitfly/eth2-beaconchain-explorer#1577] opened 2022-09-23 16:24 UTC
Missed attestations do occasionally occur and they're not a high concern, but knowing when a threshold of missed attestations has occurred can provide data for rapid response without notification fatigue. I'm requesting a "missed attestation threshold" (maybe a default of three consecutive missed attestations) to notify the user when it's likely that their validator is down. I'm not sure if the number needs to be user-configurable, maybe a simple toggle for "notify me after 3 missed attestations".

**Comment by Buttaa** [comment] 2022-09-23 16:26
hi, It's on our todo -- duplicate of https://github.com/gobitfly/eth2-beaconchain-explorer/issues/1158

**Closed by Buttaa** 2022-09-23 16:26 UTC

**Comment by superphiz** [comment] 2022-09-23 16:31
Thanks Butta!
